// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

package com.tenth.nft.protobuf;

public final class NftPlayer {
  private NftPlayer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ASSETS_BELONGS_UPDATE_ICOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ruixi.tpulse.convention.ASSETS_BELONGS_UPDATE_IC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 uid = 1;</code>
     * @return Whether the uid field is set.
     */
    boolean hasUid();
    /**
     * <code>required int64 uid = 1;</code>
     * @return The uid.
     */
    long getUid();

    /**
     * <code>required int64 assetsId = 2;</code>
     * @return Whether the assetsId field is set.
     */
    boolean hasAssetsId();
    /**
     * <code>required int64 assetsId = 2;</code>
     * @return The assetsId.
     */
    long getAssetsId();

    /**
     * <code>required int64 owns = 3;</code>
     * @return Whether the owns field is set.
     */
    boolean hasOwns();
    /**
     * <code>required int64 owns = 3;</code>
     * @return The owns.
     */
    long getOwns();
  }
  /**
   * Protobuf type {@code com.ruixi.tpulse.convention.ASSETS_BELONGS_UPDATE_IC}
   */
  public static final class ASSETS_BELONGS_UPDATE_IC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ruixi.tpulse.convention.ASSETS_BELONGS_UPDATE_IC)
      ASSETS_BELONGS_UPDATE_ICOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ASSETS_BELONGS_UPDATE_IC.newBuilder() to construct.
    private ASSETS_BELONGS_UPDATE_IC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ASSETS_BELONGS_UPDATE_IC() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ASSETS_BELONGS_UPDATE_IC();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ASSETS_BELONGS_UPDATE_IC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              assetsId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              owns_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tenth.nft.protobuf.NftPlayer.internal_static_com_ruixi_tpulse_convention_ASSETS_BELONGS_UPDATE_IC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tenth.nft.protobuf.NftPlayer.internal_static_com_ruixi_tpulse_convention_ASSETS_BELONGS_UPDATE_IC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC.class, com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>required int64 uid = 1;</code>
     * @return Whether the uid field is set.
     */
    @java.lang.Override
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }

    public static final int ASSETSID_FIELD_NUMBER = 2;
    private long assetsId_;
    /**
     * <code>required int64 assetsId = 2;</code>
     * @return Whether the assetsId field is set.
     */
    @java.lang.Override
    public boolean hasAssetsId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int64 assetsId = 2;</code>
     * @return The assetsId.
     */
    @java.lang.Override
    public long getAssetsId() {
      return assetsId_;
    }

    public static final int OWNS_FIELD_NUMBER = 3;
    private long owns_;
    /**
     * <code>required int64 owns = 3;</code>
     * @return Whether the owns field is set.
     */
    @java.lang.Override
    public boolean hasOwns() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int64 owns = 3;</code>
     * @return The owns.
     */
    @java.lang.Override
    public long getOwns() {
      return owns_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAssetsId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOwns()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, uid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, assetsId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, owns_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, assetsId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, owns_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC)) {
        return super.equals(obj);
      }
      com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC other = (com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC) obj;

      if (hasUid() != other.hasUid()) return false;
      if (hasUid()) {
        if (getUid()
            != other.getUid()) return false;
      }
      if (hasAssetsId() != other.hasAssetsId()) return false;
      if (hasAssetsId()) {
        if (getAssetsId()
            != other.getAssetsId()) return false;
      }
      if (hasOwns() != other.hasOwns()) return false;
      if (hasOwns()) {
        if (getOwns()
            != other.getOwns()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUid());
      }
      if (hasAssetsId()) {
        hash = (37 * hash) + ASSETSID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAssetsId());
      }
      if (hasOwns()) {
        hash = (37 * hash) + OWNS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOwns());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ruixi.tpulse.convention.ASSETS_BELONGS_UPDATE_IC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ruixi.tpulse.convention.ASSETS_BELONGS_UPDATE_IC)
        com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_ICOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tenth.nft.protobuf.NftPlayer.internal_static_com_ruixi_tpulse_convention_ASSETS_BELONGS_UPDATE_IC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tenth.nft.protobuf.NftPlayer.internal_static_com_ruixi_tpulse_convention_ASSETS_BELONGS_UPDATE_IC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC.class, com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC.Builder.class);
      }

      // Construct using com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        assetsId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        owns_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tenth.nft.protobuf.NftPlayer.internal_static_com_ruixi_tpulse_convention_ASSETS_BELONGS_UPDATE_IC_descriptor;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC getDefaultInstanceForType() {
        return com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC.getDefaultInstance();
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC build() {
        com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC buildPartial() {
        com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC result = new com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uid_ = uid_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.assetsId_ = assetsId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.owns_ = owns_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC) {
          return mergeFrom((com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC other) {
        if (other == com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasAssetsId()) {
          setAssetsId(other.getAssetsId());
        }
        if (other.hasOwns()) {
          setOwns(other.getOwns());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasUid()) {
          return false;
        }
        if (!hasAssetsId()) {
          return false;
        }
        if (!hasOwns()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long uid_ ;
      /**
       * <code>required int64 uid = 1;</code>
       * @return Whether the uid field is set.
       */
      @java.lang.Override
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 uid = 1;</code>
       * @return The uid.
       */
      @java.lang.Override
      public long getUid() {
        return uid_;
      }
      /**
       * <code>required int64 uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        onChanged();
        return this;
      }

      private long assetsId_ ;
      /**
       * <code>required int64 assetsId = 2;</code>
       * @return Whether the assetsId field is set.
       */
      @java.lang.Override
      public boolean hasAssetsId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int64 assetsId = 2;</code>
       * @return The assetsId.
       */
      @java.lang.Override
      public long getAssetsId() {
        return assetsId_;
      }
      /**
       * <code>required int64 assetsId = 2;</code>
       * @param value The assetsId to set.
       * @return This builder for chaining.
       */
      public Builder setAssetsId(long value) {
        bitField0_ |= 0x00000002;
        assetsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 assetsId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAssetsId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        assetsId_ = 0L;
        onChanged();
        return this;
      }

      private long owns_ ;
      /**
       * <code>required int64 owns = 3;</code>
       * @return Whether the owns field is set.
       */
      @java.lang.Override
      public boolean hasOwns() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int64 owns = 3;</code>
       * @return The owns.
       */
      @java.lang.Override
      public long getOwns() {
        return owns_;
      }
      /**
       * <code>required int64 owns = 3;</code>
       * @param value The owns to set.
       * @return This builder for chaining.
       */
      public Builder setOwns(long value) {
        bitField0_ |= 0x00000004;
        owns_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 owns = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwns() {
        bitField0_ = (bitField0_ & ~0x00000004);
        owns_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ruixi.tpulse.convention.ASSETS_BELONGS_UPDATE_IC)
    }

    // @@protoc_insertion_point(class_scope:com.ruixi.tpulse.convention.ASSETS_BELONGS_UPDATE_IC)
    private static final com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC();
    }

    public static com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ASSETS_BELONGS_UPDATE_IC>
        PARSER = new com.google.protobuf.AbstractParser<ASSETS_BELONGS_UPDATE_IC>() {
      @java.lang.Override
      public ASSETS_BELONGS_UPDATE_IC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ASSETS_BELONGS_UPDATE_IC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ASSETS_BELONGS_UPDATE_IC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ASSETS_BELONGS_UPDATE_IC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tenth.nft.protobuf.NftPlayer.ASSETS_BELONGS_UPDATE_IC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruixi_tpulse_convention_ASSETS_BELONGS_UPDATE_IC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruixi_tpulse_convention_ASSETS_BELONGS_UPDATE_IC_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014player.proto\022\033com.ruixi.tpulse.convent" +
      "ion\"G\n\030ASSETS_BELONGS_UPDATE_IC\022\013\n\003uid\030\001" +
      " \002(\003\022\020\n\010assetsId\030\002 \002(\003\022\014\n\004owns\030\003 \002(\003B#\n\026" +
      "com.tenth.nft.protobufB\tNftPlayer"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ruixi_tpulse_convention_ASSETS_BELONGS_UPDATE_IC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ruixi_tpulse_convention_ASSETS_BELONGS_UPDATE_IC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruixi_tpulse_convention_ASSETS_BELONGS_UPDATE_IC_descriptor,
        new java.lang.String[] { "Uid", "AssetsId", "Owns", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
