// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nft-web3-exchange.proto

package com.tenth.nft.protobuf;

public final class NftWeb3Exchange {
  private NftWeb3Exchange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WEB3_PAYMENT_CONFIRM_ICOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 assetsId = 1;</code>
     * @return Whether the assetsId field is set.
     */
    boolean hasAssetsId();
    /**
     * <code>required int64 assetsId = 1;</code>
     * @return The assetsId.
     */
    long getAssetsId();

    /**
     * <code>required string orderId = 2;</code>
     * @return Whether the orderId field is set.
     */
    boolean hasOrderId();
    /**
     * <code>required string orderId = 2;</code>
     * @return The orderId.
     */
    java.lang.String getOrderId();
    /**
     * <code>required string orderId = 2;</code>
     * @return The bytes for orderId.
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    /**
     * <code>required string state = 3;</code>
     * @return Whether the state field is set.
     */
    boolean hasState();
    /**
     * <code>required string state = 3;</code>
     * @return The state.
     */
    java.lang.String getState();
    /**
     * <code>required string state = 3;</code>
     * @return The bytes for state.
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>required string txn = 4;</code>
     * @return Whether the txn field is set.
     */
    boolean hasTxn();
    /**
     * <code>required string txn = 4;</code>
     * @return The txn.
     */
    java.lang.String getTxn();
    /**
     * <code>required string txn = 4;</code>
     * @return The bytes for txn.
     */
    com.google.protobuf.ByteString
        getTxnBytes();
  }
  /**
   * Protobuf type {@code com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IC}
   */
  public static final class WEB3_PAYMENT_CONFIRM_IC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IC)
      WEB3_PAYMENT_CONFIRM_ICOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WEB3_PAYMENT_CONFIRM_IC.newBuilder() to construct.
    private WEB3_PAYMENT_CONFIRM_IC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WEB3_PAYMENT_CONFIRM_IC() {
      orderId_ = "";
      state_ = "";
      txn_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WEB3_PAYMENT_CONFIRM_IC();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WEB3_PAYMENT_CONFIRM_IC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              assetsId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              orderId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              state_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              txn_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC.class, com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC.Builder.class);
    }

    private int bitField0_;
    public static final int ASSETSID_FIELD_NUMBER = 1;
    private long assetsId_;
    /**
     * <code>required int64 assetsId = 1;</code>
     * @return Whether the assetsId field is set.
     */
    @java.lang.Override
    public boolean hasAssetsId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 assetsId = 1;</code>
     * @return The assetsId.
     */
    @java.lang.Override
    public long getAssetsId() {
      return assetsId_;
    }

    public static final int ORDERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object orderId_;
    /**
     * <code>required string orderId = 2;</code>
     * @return Whether the orderId field is set.
     */
    @java.lang.Override
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string orderId = 2;</code>
     * @return The orderId.
     */
    @java.lang.Override
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string orderId = 2;</code>
     * @return The bytes for orderId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object state_;
    /**
     * <code>required string state = 3;</code>
     * @return Whether the state field is set.
     */
    @java.lang.Override
    public boolean hasState() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string state = 3;</code>
     * @return The state.
     */
    @java.lang.Override
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          state_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string state = 3;</code>
     * @return The bytes for state.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TXN_FIELD_NUMBER = 4;
    private volatile java.lang.Object txn_;
    /**
     * <code>required string txn = 4;</code>
     * @return Whether the txn field is set.
     */
    @java.lang.Override
    public boolean hasTxn() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string txn = 4;</code>
     * @return The txn.
     */
    @java.lang.Override
    public java.lang.String getTxn() {
      java.lang.Object ref = txn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          txn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string txn = 4;</code>
     * @return The bytes for txn.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTxnBytes() {
      java.lang.Object ref = txn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAssetsId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTxn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, assetsId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, state_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, txn_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, assetsId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, state_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, txn_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC)) {
        return super.equals(obj);
      }
      com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC other = (com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC) obj;

      if (hasAssetsId() != other.hasAssetsId()) return false;
      if (hasAssetsId()) {
        if (getAssetsId()
            != other.getAssetsId()) return false;
      }
      if (hasOrderId() != other.hasOrderId()) return false;
      if (hasOrderId()) {
        if (!getOrderId()
            .equals(other.getOrderId())) return false;
      }
      if (hasState() != other.hasState()) return false;
      if (hasState()) {
        if (!getState()
            .equals(other.getState())) return false;
      }
      if (hasTxn() != other.hasTxn()) return false;
      if (hasTxn()) {
        if (!getTxn()
            .equals(other.getTxn())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAssetsId()) {
        hash = (37 * hash) + ASSETSID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAssetsId());
      }
      if (hasOrderId()) {
        hash = (37 * hash) + ORDERID_FIELD_NUMBER;
        hash = (53 * hash) + getOrderId().hashCode();
      }
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
      }
      if (hasTxn()) {
        hash = (37 * hash) + TXN_FIELD_NUMBER;
        hash = (53 * hash) + getTxn().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IC)
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_ICOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC.class, com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC.Builder.class);
      }

      // Construct using com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        assetsId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        orderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        txn_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IC_descriptor;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC getDefaultInstanceForType() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC.getDefaultInstance();
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC build() {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC buildPartial() {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC result = new com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.assetsId_ = assetsId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.orderId_ = orderId_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.txn_ = txn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC) {
          return mergeFrom((com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC other) {
        if (other == com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC.getDefaultInstance()) return this;
        if (other.hasAssetsId()) {
          setAssetsId(other.getAssetsId());
        }
        if (other.hasOrderId()) {
          bitField0_ |= 0x00000002;
          orderId_ = other.orderId_;
          onChanged();
        }
        if (other.hasState()) {
          bitField0_ |= 0x00000004;
          state_ = other.state_;
          onChanged();
        }
        if (other.hasTxn()) {
          bitField0_ |= 0x00000008;
          txn_ = other.txn_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAssetsId()) {
          return false;
        }
        if (!hasOrderId()) {
          return false;
        }
        if (!hasState()) {
          return false;
        }
        if (!hasTxn()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long assetsId_ ;
      /**
       * <code>required int64 assetsId = 1;</code>
       * @return Whether the assetsId field is set.
       */
      @java.lang.Override
      public boolean hasAssetsId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 assetsId = 1;</code>
       * @return The assetsId.
       */
      @java.lang.Override
      public long getAssetsId() {
        return assetsId_;
      }
      /**
       * <code>required int64 assetsId = 1;</code>
       * @param value The assetsId to set.
       * @return This builder for chaining.
       */
      public Builder setAssetsId(long value) {
        bitField0_ |= 0x00000001;
        assetsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 assetsId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAssetsId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        assetsId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>required string orderId = 2;</code>
       * @return Whether the orderId field is set.
       */
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string orderId = 2;</code>
       * @return The orderId.
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            orderId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string orderId = 2;</code>
       * @return The bytes for orderId.
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string orderId = 2;</code>
       * @param value The orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string orderId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>required string orderId = 2;</code>
       * @param value The bytes for orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        orderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>required string state = 3;</code>
       * @return Whether the state field is set.
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string state = 3;</code>
       * @return The state.
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            state_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string state = 3;</code>
       * @return The bytes for state.
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string state = 3;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 3;</code>
       * @param value The bytes for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        state_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object txn_ = "";
      /**
       * <code>required string txn = 4;</code>
       * @return Whether the txn field is set.
       */
      public boolean hasTxn() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string txn = 4;</code>
       * @return The txn.
       */
      public java.lang.String getTxn() {
        java.lang.Object ref = txn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            txn_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string txn = 4;</code>
       * @return The bytes for txn.
       */
      public com.google.protobuf.ByteString
          getTxnBytes() {
        java.lang.Object ref = txn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string txn = 4;</code>
       * @param value The txn to set.
       * @return This builder for chaining.
       */
      public Builder setTxn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        txn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string txn = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxn() {
        bitField0_ = (bitField0_ & ~0x00000008);
        txn_ = getDefaultInstance().getTxn();
        onChanged();
        return this;
      }
      /**
       * <code>required string txn = 4;</code>
       * @param value The bytes for txn to set.
       * @return This builder for chaining.
       */
      public Builder setTxnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        txn_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IC)
    }

    // @@protoc_insertion_point(class_scope:com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IC)
    private static final com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC();
    }

    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WEB3_PAYMENT_CONFIRM_IC>
        PARSER = new com.google.protobuf.AbstractParser<WEB3_PAYMENT_CONFIRM_IC>() {
      @java.lang.Override
      public WEB3_PAYMENT_CONFIRM_IC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WEB3_PAYMENT_CONFIRM_IC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WEB3_PAYMENT_CONFIRM_IC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WEB3_PAYMENT_CONFIRM_IC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WEB3_PAYMENT_CONFIRM_ISOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IS)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IS}
   */
  public static final class WEB3_PAYMENT_CONFIRM_IS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IS)
      WEB3_PAYMENT_CONFIRM_ISOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WEB3_PAYMENT_CONFIRM_IS.newBuilder() to construct.
    private WEB3_PAYMENT_CONFIRM_IS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WEB3_PAYMENT_CONFIRM_IS() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WEB3_PAYMENT_CONFIRM_IS();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WEB3_PAYMENT_CONFIRM_IS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IS_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS.class, com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS)) {
        return super.equals(obj);
      }
      com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS other = (com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IS)
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_ISOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IS_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS.class, com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS.Builder.class);
      }

      // Construct using com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IS_descriptor;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS getDefaultInstanceForType() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS.getDefaultInstance();
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS build() {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS buildPartial() {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS result = new com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS) {
          return mergeFrom((com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS other) {
        if (other == com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IS)
    }

    // @@protoc_insertion_point(class_scope:com.ruixi.tpulse.convention.WEB3_PAYMENT_CONFIRM_IS)
    private static final com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS();
    }

    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WEB3_PAYMENT_CONFIRM_IS>
        PARSER = new com.google.protobuf.AbstractParser<WEB3_PAYMENT_CONFIRM_IS>() {
      @java.lang.Override
      public WEB3_PAYMENT_CONFIRM_IS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WEB3_PAYMENT_CONFIRM_IS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WEB3_PAYMENT_CONFIRM_IS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WEB3_PAYMENT_CONFIRM_IS> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_CONFIRM_IS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WEB3_PAYMENT_STATE_ICOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IC)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IC}
   */
  public static final class WEB3_PAYMENT_STATE_IC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IC)
      WEB3_PAYMENT_STATE_ICOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WEB3_PAYMENT_STATE_IC.newBuilder() to construct.
    private WEB3_PAYMENT_STATE_IC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WEB3_PAYMENT_STATE_IC() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WEB3_PAYMENT_STATE_IC();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WEB3_PAYMENT_STATE_IC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC.class, com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC)) {
        return super.equals(obj);
      }
      com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC other = (com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IC)
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_ICOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC.class, com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC.Builder.class);
      }

      // Construct using com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IC_descriptor;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC getDefaultInstanceForType() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC.getDefaultInstance();
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC build() {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC buildPartial() {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC result = new com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC) {
          return mergeFrom((com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC other) {
        if (other == com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IC)
    }

    // @@protoc_insertion_point(class_scope:com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IC)
    private static final com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC();
    }

    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WEB3_PAYMENT_STATE_IC>
        PARSER = new com.google.protobuf.AbstractParser<WEB3_PAYMENT_STATE_IC>() {
      @java.lang.Override
      public WEB3_PAYMENT_STATE_IC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WEB3_PAYMENT_STATE_IC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WEB3_PAYMENT_STATE_IC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WEB3_PAYMENT_STATE_IC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WEB3_PAYMENT_STATE_ISOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IS)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IS}
   */
  public static final class WEB3_PAYMENT_STATE_IS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IS)
      WEB3_PAYMENT_STATE_ISOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WEB3_PAYMENT_STATE_IS.newBuilder() to construct.
    private WEB3_PAYMENT_STATE_IS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WEB3_PAYMENT_STATE_IS() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WEB3_PAYMENT_STATE_IS();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WEB3_PAYMENT_STATE_IS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IS_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS.class, com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS)) {
        return super.equals(obj);
      }
      com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS other = (com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IS)
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_ISOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IS_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS.class, com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS.Builder.class);
      }

      // Construct using com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IS_descriptor;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS getDefaultInstanceForType() {
        return com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS.getDefaultInstance();
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS build() {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS buildPartial() {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS result = new com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS) {
          return mergeFrom((com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS other) {
        if (other == com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IS)
    }

    // @@protoc_insertion_point(class_scope:com.ruixi.tpulse.convention.WEB3_PAYMENT_STATE_IS)
    private static final com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS();
    }

    public static com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WEB3_PAYMENT_STATE_IS>
        PARSER = new com.google.protobuf.AbstractParser<WEB3_PAYMENT_STATE_IS>() {
      @java.lang.Override
      public WEB3_PAYMENT_STATE_IS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WEB3_PAYMENT_STATE_IS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WEB3_PAYMENT_STATE_IS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WEB3_PAYMENT_STATE_IS> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tenth.nft.protobuf.NftWeb3Exchange.WEB3_PAYMENT_STATE_IS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IS_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027nft-web3-exchange.proto\022\033com.ruixi.tpu" +
      "lse.convention\"X\n\027WEB3_PAYMENT_CONFIRM_I" +
      "C\022\020\n\010assetsId\030\001 \002(\003\022\017\n\007orderId\030\002 \002(\t\022\r\n\005" +
      "state\030\003 \002(\t\022\013\n\003txn\030\004 \002(\t\"\031\n\027WEB3_PAYMENT" +
      "_CONFIRM_IS\"\027\n\025WEB3_PAYMENT_STATE_IC\"\027\n\025" +
      "WEB3_PAYMENT_STATE_ISB)\n\026com.tenth.nft.p" +
      "rotobufB\017NftWeb3Exchange"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IC_descriptor,
        new java.lang.String[] { "AssetsId", "OrderId", "State", "Txn", });
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IS_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_CONFIRM_IS_descriptor,
        new java.lang.String[] { });
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IC_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IC_descriptor,
        new java.lang.String[] { });
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IS_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruixi_tpulse_convention_WEB3_PAYMENT_STATE_IS_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
