// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package com.tenth.nft.protobuf;

public final class Search {
  private Search() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NFT_CATEGORY_REBUILD_ICOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ruixi.tpulse.convention.NFT_CATEGORY_REBUILD_IC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 version = 1;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <code>required int64 version = 1;</code>
     * @return The version.
     */
    long getVersion();
  }
  /**
   * Protobuf type {@code com.ruixi.tpulse.convention.NFT_CATEGORY_REBUILD_IC}
   */
  public static final class NFT_CATEGORY_REBUILD_IC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ruixi.tpulse.convention.NFT_CATEGORY_REBUILD_IC)
      NFT_CATEGORY_REBUILD_ICOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NFT_CATEGORY_REBUILD_IC.newBuilder() to construct.
    private NFT_CATEGORY_REBUILD_IC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NFT_CATEGORY_REBUILD_IC() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NFT_CATEGORY_REBUILD_IC();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NFT_CATEGORY_REBUILD_IC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_CATEGORY_REBUILD_IC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_CATEGORY_REBUILD_IC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC.class, com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    /**
     * <code>required int64 version = 1;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, version_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, version_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC)) {
        return super.equals(obj);
      }
      com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC other = (com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC) obj;

      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getVersion());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ruixi.tpulse.convention.NFT_CATEGORY_REBUILD_IC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ruixi.tpulse.convention.NFT_CATEGORY_REBUILD_IC)
        com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_ICOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_CATEGORY_REBUILD_IC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_CATEGORY_REBUILD_IC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC.class, com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC.Builder.class);
      }

      // Construct using com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_CATEGORY_REBUILD_IC_descriptor;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC getDefaultInstanceForType() {
        return com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC.getDefaultInstance();
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC build() {
        com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC buildPartial() {
        com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC result = new com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC) {
          return mergeFrom((com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC other) {
        if (other == com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long version_ ;
      /**
       * <code>required int64 version = 1;</code>
       * @return Whether the version field is set.
       */
      @java.lang.Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public long getVersion() {
        return version_;
      }
      /**
       * <code>required int64 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ruixi.tpulse.convention.NFT_CATEGORY_REBUILD_IC)
    }

    // @@protoc_insertion_point(class_scope:com.ruixi.tpulse.convention.NFT_CATEGORY_REBUILD_IC)
    private static final com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC();
    }

    public static com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NFT_CATEGORY_REBUILD_IC>
        PARSER = new com.google.protobuf.AbstractParser<NFT_CATEGORY_REBUILD_IC>() {
      @java.lang.Override
      public NFT_CATEGORY_REBUILD_IC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NFT_CATEGORY_REBUILD_IC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NFT_CATEGORY_REBUILD_IC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NFT_CATEGORY_REBUILD_IC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tenth.nft.protobuf.Search.NFT_CATEGORY_REBUILD_IC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NFT_COLLECTION_REBUILD_ICOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ruixi.tpulse.convention.NFT_COLLECTION_REBUILD_IC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 collectionId = 1;</code>
     * @return Whether the collectionId field is set.
     */
    boolean hasCollectionId();
    /**
     * <code>required int64 collectionId = 1;</code>
     * @return The collectionId.
     */
    long getCollectionId();
  }
  /**
   * Protobuf type {@code com.ruixi.tpulse.convention.NFT_COLLECTION_REBUILD_IC}
   */
  public static final class NFT_COLLECTION_REBUILD_IC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ruixi.tpulse.convention.NFT_COLLECTION_REBUILD_IC)
      NFT_COLLECTION_REBUILD_ICOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NFT_COLLECTION_REBUILD_IC.newBuilder() to construct.
    private NFT_COLLECTION_REBUILD_IC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NFT_COLLECTION_REBUILD_IC() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NFT_COLLECTION_REBUILD_IC();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NFT_COLLECTION_REBUILD_IC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              collectionId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_COLLECTION_REBUILD_IC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_COLLECTION_REBUILD_IC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC.class, com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC.Builder.class);
    }

    private int bitField0_;
    public static final int COLLECTIONID_FIELD_NUMBER = 1;
    private long collectionId_;
    /**
     * <code>required int64 collectionId = 1;</code>
     * @return Whether the collectionId field is set.
     */
    @java.lang.Override
    public boolean hasCollectionId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 collectionId = 1;</code>
     * @return The collectionId.
     */
    @java.lang.Override
    public long getCollectionId() {
      return collectionId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCollectionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, collectionId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, collectionId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC)) {
        return super.equals(obj);
      }
      com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC other = (com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC) obj;

      if (hasCollectionId() != other.hasCollectionId()) return false;
      if (hasCollectionId()) {
        if (getCollectionId()
            != other.getCollectionId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCollectionId()) {
        hash = (37 * hash) + COLLECTIONID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCollectionId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ruixi.tpulse.convention.NFT_COLLECTION_REBUILD_IC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ruixi.tpulse.convention.NFT_COLLECTION_REBUILD_IC)
        com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_ICOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_COLLECTION_REBUILD_IC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_COLLECTION_REBUILD_IC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC.class, com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC.Builder.class);
      }

      // Construct using com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        collectionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_COLLECTION_REBUILD_IC_descriptor;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC getDefaultInstanceForType() {
        return com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC.getDefaultInstance();
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC build() {
        com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC buildPartial() {
        com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC result = new com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.collectionId_ = collectionId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC) {
          return mergeFrom((com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC other) {
        if (other == com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC.getDefaultInstance()) return this;
        if (other.hasCollectionId()) {
          setCollectionId(other.getCollectionId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCollectionId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long collectionId_ ;
      /**
       * <code>required int64 collectionId = 1;</code>
       * @return Whether the collectionId field is set.
       */
      @java.lang.Override
      public boolean hasCollectionId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 collectionId = 1;</code>
       * @return The collectionId.
       */
      @java.lang.Override
      public long getCollectionId() {
        return collectionId_;
      }
      /**
       * <code>required int64 collectionId = 1;</code>
       * @param value The collectionId to set.
       * @return This builder for chaining.
       */
      public Builder setCollectionId(long value) {
        bitField0_ |= 0x00000001;
        collectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 collectionId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCollectionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        collectionId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ruixi.tpulse.convention.NFT_COLLECTION_REBUILD_IC)
    }

    // @@protoc_insertion_point(class_scope:com.ruixi.tpulse.convention.NFT_COLLECTION_REBUILD_IC)
    private static final com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC();
    }

    public static com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NFT_COLLECTION_REBUILD_IC>
        PARSER = new com.google.protobuf.AbstractParser<NFT_COLLECTION_REBUILD_IC>() {
      @java.lang.Override
      public NFT_COLLECTION_REBUILD_IC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NFT_COLLECTION_REBUILD_IC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NFT_COLLECTION_REBUILD_IC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NFT_COLLECTION_REBUILD_IC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tenth.nft.protobuf.Search.NFT_COLLECTION_REBUILD_IC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NFT_ITEM_REBUILD_ICOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ruixi.tpulse.convention.NFT_ITEM_REBUILD_IC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 collectionId = 1;</code>
     * @return Whether the collectionId field is set.
     */
    boolean hasCollectionId();
    /**
     * <code>required int64 collectionId = 1;</code>
     * @return The collectionId.
     */
    long getCollectionId();
  }
  /**
   * Protobuf type {@code com.ruixi.tpulse.convention.NFT_ITEM_REBUILD_IC}
   */
  public static final class NFT_ITEM_REBUILD_IC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ruixi.tpulse.convention.NFT_ITEM_REBUILD_IC)
      NFT_ITEM_REBUILD_ICOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NFT_ITEM_REBUILD_IC.newBuilder() to construct.
    private NFT_ITEM_REBUILD_IC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NFT_ITEM_REBUILD_IC() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NFT_ITEM_REBUILD_IC();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NFT_ITEM_REBUILD_IC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              collectionId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_ITEM_REBUILD_IC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_ITEM_REBUILD_IC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC.class, com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC.Builder.class);
    }

    private int bitField0_;
    public static final int COLLECTIONID_FIELD_NUMBER = 1;
    private long collectionId_;
    /**
     * <code>required int64 collectionId = 1;</code>
     * @return Whether the collectionId field is set.
     */
    @java.lang.Override
    public boolean hasCollectionId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 collectionId = 1;</code>
     * @return The collectionId.
     */
    @java.lang.Override
    public long getCollectionId() {
      return collectionId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCollectionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, collectionId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, collectionId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC)) {
        return super.equals(obj);
      }
      com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC other = (com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC) obj;

      if (hasCollectionId() != other.hasCollectionId()) return false;
      if (hasCollectionId()) {
        if (getCollectionId()
            != other.getCollectionId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCollectionId()) {
        hash = (37 * hash) + COLLECTIONID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCollectionId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ruixi.tpulse.convention.NFT_ITEM_REBUILD_IC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ruixi.tpulse.convention.NFT_ITEM_REBUILD_IC)
        com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_ICOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_ITEM_REBUILD_IC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_ITEM_REBUILD_IC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC.class, com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC.Builder.class);
      }

      // Construct using com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        collectionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tenth.nft.protobuf.Search.internal_static_com_ruixi_tpulse_convention_NFT_ITEM_REBUILD_IC_descriptor;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC getDefaultInstanceForType() {
        return com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC.getDefaultInstance();
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC build() {
        com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC buildPartial() {
        com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC result = new com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.collectionId_ = collectionId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC) {
          return mergeFrom((com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC other) {
        if (other == com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC.getDefaultInstance()) return this;
        if (other.hasCollectionId()) {
          setCollectionId(other.getCollectionId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCollectionId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long collectionId_ ;
      /**
       * <code>required int64 collectionId = 1;</code>
       * @return Whether the collectionId field is set.
       */
      @java.lang.Override
      public boolean hasCollectionId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 collectionId = 1;</code>
       * @return The collectionId.
       */
      @java.lang.Override
      public long getCollectionId() {
        return collectionId_;
      }
      /**
       * <code>required int64 collectionId = 1;</code>
       * @param value The collectionId to set.
       * @return This builder for chaining.
       */
      public Builder setCollectionId(long value) {
        bitField0_ |= 0x00000001;
        collectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 collectionId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCollectionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        collectionId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ruixi.tpulse.convention.NFT_ITEM_REBUILD_IC)
    }

    // @@protoc_insertion_point(class_scope:com.ruixi.tpulse.convention.NFT_ITEM_REBUILD_IC)
    private static final com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC();
    }

    public static com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NFT_ITEM_REBUILD_IC>
        PARSER = new com.google.protobuf.AbstractParser<NFT_ITEM_REBUILD_IC>() {
      @java.lang.Override
      public NFT_ITEM_REBUILD_IC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NFT_ITEM_REBUILD_IC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NFT_ITEM_REBUILD_IC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NFT_ITEM_REBUILD_IC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tenth.nft.protobuf.Search.NFT_ITEM_REBUILD_IC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruixi_tpulse_convention_NFT_CATEGORY_REBUILD_IC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruixi_tpulse_convention_NFT_CATEGORY_REBUILD_IC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruixi_tpulse_convention_NFT_COLLECTION_REBUILD_IC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruixi_tpulse_convention_NFT_COLLECTION_REBUILD_IC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruixi_tpulse_convention_NFT_ITEM_REBUILD_IC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruixi_tpulse_convention_NFT_ITEM_REBUILD_IC_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014search.proto\022\033com.ruixi.tpulse.convent" +
      "ion\"*\n\027NFT_CATEGORY_REBUILD_IC\022\017\n\007versio" +
      "n\030\001 \002(\003\"1\n\031NFT_COLLECTION_REBUILD_IC\022\024\n\014" +
      "collectionId\030\001 \002(\003\"+\n\023NFT_ITEM_REBUILD_I" +
      "C\022\024\n\014collectionId\030\001 \002(\003B\030\n\026com.tenth.nft" +
      ".protobuf"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ruixi_tpulse_convention_NFT_CATEGORY_REBUILD_IC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ruixi_tpulse_convention_NFT_CATEGORY_REBUILD_IC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruixi_tpulse_convention_NFT_CATEGORY_REBUILD_IC_descriptor,
        new java.lang.String[] { "Version", });
    internal_static_com_ruixi_tpulse_convention_NFT_COLLECTION_REBUILD_IC_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ruixi_tpulse_convention_NFT_COLLECTION_REBUILD_IC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruixi_tpulse_convention_NFT_COLLECTION_REBUILD_IC_descriptor,
        new java.lang.String[] { "CollectionId", });
    internal_static_com_ruixi_tpulse_convention_NFT_ITEM_REBUILD_IC_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ruixi_tpulse_convention_NFT_ITEM_REBUILD_IC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruixi_tpulse_convention_NFT_ITEM_REBUILD_IC_descriptor,
        new java.lang.String[] { "CollectionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
